name: Snake Animation

on:
  push:
    branches:
      - main

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Snake Animation
        uses: Platane/snk@master
        id: snake
        with:
          png_width: 800
          png_height: 600
          number_of_frames: 36
          speed: 10
          emoji: "🐍"
          color: "#00ff00"

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: 'snake.gif'